# Generated by Django 2.2.10 on 2021-04-28 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Poll name')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Poll start date')),
                ('end_date', models.DateField(default=datetime.date(2100, 12, 31), verbose_name='Poll end date')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User iD')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Question text')),
                ('question_type', models.IntegerField(choices=[(1, 'Text answer'), (2, 'One answer select'), (3, 'More than one answer select')], verbose_name='Question type')),
                ('answer_variants', models.TextField(blank=True, max_length=1000, verbose_name='Answer variants')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Correct answer')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_questions', to='poll.Poll', verbose_name='Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='poll.Question', verbose_name='Question')),
                ('user_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_answers', to='poll.UserPoll', verbose_name='User poll')),
            ],
        ),
    ]
