# Generated by Django 2.2.10 on 2021-04-27 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Poll name')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Poll start date')),
                ('end_date', models.DateField(default=datetime.date(2100, 12, 31), verbose_name='Poll end date')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
        ),
    ]
